version: '3.8'
services:
  go-api-service:
    container_name: go-api-service
    image: wi1123/go-api-service:latest
    ports:
      - "80:8000"
    volumes:
      - ./config/config.yml:/app/config/config.yml:ro 
    restart: always