version: '3.8'
services:
  go-api-service:
    container_name: go-api-service
    build:
      context: .
      dockerfile: ./cmd/go-api-service/Dockerfile
    ports:
      - "80:8000"
    volumes:
      - ./config/config.yml:/app/config/config.yml:ro 
    restart: always