version: '3.8'

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.3.0
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
  kafka:
    image: confluentinc/cp-kafka:7.3.0
    container_name: kafka
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,PLAINTEXT_INTERNAL://kafka:29092
      KAFKA_INTER_BROKER_LISTENER_NAME: 'PLAINTEXT_INTERNAL'
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"

  go-ingestor:
    container_name: go-ingestor
    build:
      context: .
      dockerfile: ./cmd/go-ingestor/Dockerfile
    depends_on:
      - kafka
    volumes:
      - ./config/config.yml:/app/config/config.yml:ro 
  go-processor:
    container_name: go-processor
    build:
      context: .
      dockerfile: ./cmd/go-processor/Dockerfile
    depends_on:
      - kafka
    volumes:
      - ./config/config.yml:/app/config/config.yml:ro 
  go-api-service:
    container_name: go-api-service
    build:
      context: .
      dockerfile: ./cmd/go-api-service/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./config/config.yml:/app/config/config.yml:ro 